### ISSUE TITLE
Unexpected `'ERROR: levenshtein argument exceeds maximum length of 255 characters'`

### ISSUE THREAD

**Issue by matkoniecz** [osmlab/maproulette-python-client#103]
* **Do you want to request a *feature* or report a *bug*?**
  - [x] bug report
  - [ ] feature request

* **What is the current behavior?**

Unexpected `'ERROR: levenshtein argument exceeds maximum length of 255 characters'`

```
Traceback (most recent call last):
  File "/home/mateusz/Documents/install_moje/OSM_software/wikipedia-tag-validator/maproulette_challenge_creation.py", line 4, in <module>
    api.find_project("fix broken Wikipedia tags")
  File "/home/mateusz/.local/lib/python3.10/site-packages/maproulette/api/project.py", line 50, in find_project
    response = self.get(
  File "/home/mateusz/.local/lib/python3.10/site-packages/maproulette/api/maproulette_server.py", line 73, in get
    raise HttpError(
maproulette.api.errors.HttpError: {'status': 500, 'message': 'ERROR: levenshtein argument exceeds maximum length of 255 characters'}
```

on calling

```
import maproulette
api_key = "API_KEY_SNIPPED"
api = maproulette.Project(maproulette.Configuration(api_key=api_key))
api.find_project("fix broken Wikipedia tags")
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the 
problem**

see above

* **What is the expected behavior?**

no crash

* **What is the motivation / use case for changing the behavior?**

avoiding crash

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to
 have context, eg. stackoverflow, gitter, etc)

maybe it is a server bug? Asked also on US Slack.

**Comment by jake-low** [comment]
(Reposting a comment I made on OSM US Slack, for visibility here).

This is probably caused by a bug somewhere in [MapRoulette's backend](https://github.com/maproulette/maproulette-backend). I can replicate the same error message with this curl request. It seems nearly any search string will trigger the error. Some very short strings like “a” and “e” appear to work (they at least return search results, though I haven’t checked to make sure the results match the query).

```
λ curl -i 'https://maproulette.org/api/v2/projects?search=trailheads'
HTTP/2 500
date: Fri, 11 Oct 2024 18:54:04 GMT
content-type: application/json
vary: Accept-Encoding,Origin
maproulette-request-id: 979385b9-32c5-4872-a1f1-9ab611545ab3
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=c2YME%2F%2Fq%2Fgq9oBz5ZE6uA%2BTAfYxVsoMYySgglDNRsZ%2FqoKbcb0%2Bfx8nnlT4cSqknhoMaEEyZ53q1cV4Qv6vOjznVRtAPAsGhvTdLe10dI9Cx5y%2B%2FHjMiMURtArFGPp8DFeA%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 8d110e800fb87590-SEA
alt-svc: h3=":443"; ma=86400

{"status":"KO","message":"ERROR: levenshtein argument exceeds maximum length of 255 characters"}
```

The error string “levenshtein argument exceeds maximum length…” comes from PostgreSQL. Presumably the MapRoulette backend is calling postgres’ `levenshtein` function with an argument that is too long.

The backend code that constructs the SQL query for the `/projects` endpoint is [here, in ProjectService.scala](https://github.com/maproulette/maproulette-backend/blob/main/app/org/maproulette/framework/service/ProjectService.scala#L187-L239). The code uses a query builder and I can’t tell by reading the code exactly what SQL will be run. But I’ll try to replicate this using a local backend, where I think I can use the debug logs to see the actual query and maybe find the cause of the bug.

EDIT: the `levenshtein()` call is hidden in the definition of `FuzzySearchParameter` [here](https://github.com/maproulette/maproulette-backend/blob/main/app/org/maproulette/framework/psql/filter/Parameter.scala#L211-L234).

**Comment by matkoniecz** [comment]
as it is a server bug I will close it here
